config/routes.rb
# OpenID Connect Authentication for Redmine
# Copyright (C) 2020-2021 Contargo GmbH & Co. KG
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

Rails.application.routes.draw do
  get 'oidc/login', to: 'oidc#login', as: 'oidc_login'
  get 'oidc/callback', to: 'oidc#callback', as: 'oidc_callback'
  get 'oidc/logout', to: 'oidc#logout', as: 'oidc_logout'
  get 'oidc/local_logout', to: 'oidc#local_logout', as: 'oidc_local_logout'
  get 'oidc/check_session_iframe', to: 'oidc#check_session_iframe', as: 'oidc_check_session_iframe'
end

app/views/hooks/_view_layouts_base_body_bottom.html.erb
<iframe id="redmineCheckSessionIframe" src="<%= oidc_check_session_iframe_path %>" style="display:none" onload="checkSessionPoll('redmineCheckSessionIframe')"></iframe>
<iframe id="identityProviderCheckSessionIframe" src="<%= oidc_session.check_session_iframe %>" style="display:none" onload="checkSessionPoll('identityProviderCheckSessionIframe')"></iframe>
<script type="text/javascript">
  var intervalId;

  checkSessionPoll = (function () {
      var redmineCheckSessionIframeLoaded = false;
      var identityProviderCheckSessionIframeLoaded = false;
      return function(frame) {
          if (frame == 'redmineCheckSessionIframe') redmineCheckSessionIframeLoaded = true;
          if (frame == 'identityProviderCheckSessionIframe') identityProviderCheckSessionIframeLoaded = true;
          if (redmineCheckSessionIframeLoaded && identityProviderCheckSessionIframeLoaded) {
              var redmineCheckSessionIframe = document.getElementById('redmineCheckSessionIframe').contentWindow;
              intervalId = setInterval(redmineCheckSessionIframe.checkSession, redmineCheckSessionIframe.checkInterval);
          }
      };
  })();
</script>